@startuml
title Warmhouse Container Diagram

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

Person(user, "User", "Пользователь системы warmHouse")
Person(admin, "Administrator", "Администратор системы")
System(WarmhouseSystem, "Warmhouse System", "Система управления отоплением в доме")

Container_Boundary(WarmhouseSystem, "Warmhouse System") {
  Container(SmartHomeApp, "SmartHome Application", "Go", "Система управлением отопления в доме")
  Container(TemperatureApp, "Temperature Application", "Python, Flask", "Сервис данных о температуре")
  Container(Database, "Database", "PostgreSQL", "Хранит информацию о датчиках")
}

Rel(user, SmartHomeApp, "Управление умным домом")
Rel(admin, SmartHomeApp,"Администрирование системы")
Rel(SmartHomeApp,TemperatureApp,"Получение информации о датчиках")
Rel(SmartHomeApp,Database,"Чтение/запись данных")
@enduml